# Generated by Django 3.2.8 on 2021-10-21 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211019_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[['primary school', 'Primary School'], ['secondary school', 'Secondary School'], ['Technician', 'Technician'], ['college', 'College'], ['polytechnic', 'Polytechnic'], ['university', 'University']], max_length=255)),
                ('certificate', models.CharField(choices=[('leaving school', 'leaving school'), ('0 level', '0 level'), ('NCE', 'NCE'), ('Diploma', 'Diploma'), ('OND', 'National Diploma'), ('Technician', 'Technician'), ('HND', 'Higher National Diploma'), ('BSc', 'Bachelor of Science'), ('BSEng', 'Bachelor of Engineering'), ('BTech', 'Bachelor of Technology'), ('BEdu', 'Bachelor of Education')], max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('current', models.BooleanField(default=False)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time', models.BooleanField(default=True)),
                ('part_time', models.BooleanField(default=True)),
                ('contract', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
