# Generated by Django 3.2.8 on 2021-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211202_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=6),
        ),
    ]
