# Generated by Django 3.2.8 on 2021-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspost',
            name='salary_type',
            field=models.CharField(choices=[['hourly', 'hour'], ['monthly', 'month'], ['annually', 'annual']], default='monthly', max_length=10),
            preserve_default=False,
        ),
    ]
