# Generated by Django 3.2.8 on 2021-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_jobspost_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='display_picture',
            field=models.URLField(null=True),
        ),
    ]
