# Generated by Django 3.2.8 on 2021-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employer_display_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='display_picture',
            new_name='company_logo',
        ),
    ]
