# Generated by Django 3.2.8 on 2021-12-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_display_picture_employer_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobspost',
            old_name='budget_end',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='jobspost',
            name='budget_start',
        ),
    ]
