# Generated by Django 3.2.8 on 2021-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211205_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_profile',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='hired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='reviews',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='jobspost',
            name='employer_logo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='jobspost',
            name='access',
            field=models.CharField(choices=[['public', 'public'], ['private', 'private'], ['verified', 'verified'], ['delete', 'deleted']], default='public', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobspost',
            name='salary_type',
            field=models.CharField(choices=[['hourly', 'hour'], ['monthly', 'month'], ['annually', 'annual']], max_length=10),
        ),
    ]
