# Generated by Django 3.2.8 on 2021-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211207_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
