# Generated by Django 3.2.8 on 2021-12-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_workexperience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='display_picture',
            field=models.URLField(default='https://api.workanetworks.com/media/display-picture/2/download.png'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[['Male', 'male'], ['Female', 'female']], max_length=6),
        ),
    ]
