# Generated by Django 3.2.8 on 2021-12-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211223_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='display_picture',
            field=models.URLField(default='https://api.workanetworks.com/media/display-picture/2/download.png'),
        ),
    ]
