# Generated by Django 3.2.8 on 2021-12-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.URLField(default='https://api.workanetworks.com/media/company-logo/ydxvbh3vgo/306424.png'),
        ),
    ]
