# Generated by Django 3.2.8 on 2022-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_employer_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
