# Generated by Django 3.2.8 on 2022-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_employer_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobspost',
            name='access',
            field=models.CharField(choices=[['open', 'open'], ['closed', 'closed'], ['pending', 'pending'], ['delete', 'deleted']], default='open', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobspost',
            name='salary_type',
            field=models.CharField(choices=[['hourly', 'hour'], ['daily', 'day'], ['weekly', 'week'], ['monthly', 'month'], ['annually', 'annual']], max_length=10),
        ),
    ]
