# Generated by Django 3.2.8 on 2022-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220112_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[['elementary', 'elementary'], ['high school', 'High School'], ['Technician', 'Technician'], ['college', 'College'], ['polytechnic', 'Polytechnic'], ['university', 'University']], max_length=255),
        ),
    ]
