# Generated by Django 3.2.8 on 2022-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220121_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobspost',
            name='benefit',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobspost',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
