# Generated by Django 3.2.8 on 2021-12-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0018_auto_20211220_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_uid', models.CharField(default='', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[['closed', 'closed'], ['open', 'open'], ['suspended', 'suspended']], default='open', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('timer', models.BooleanField(default=False)),
                ('submission', models.IntegerField(default=0)),
                ('timer_sec', models.IntegerField(default=0)),
                ('interview_type', models.CharField(choices=[['objective', 'objective'], ['theory', 'theory']], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interview', to='api.jobspost')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryInterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uid', models.CharField(max_length=9)),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_interview_question', to='interview.interviews')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryInterviewAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_theory_interview', to='api.employee')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_interview_answer', to='interview.interviews')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_interview_question', to='interview.theoryinterviewquestions')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveInterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uid', models.CharField(max_length=7)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_interview_question', to='interview.interviews')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveInterviewAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_obj_interview', to='api.employee')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_interview_answer', to='interview.interviews')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_interview_question', to='interview.objectiveinterviewquestions')),
            ],
        ),
    ]
