# Generated by Django 3.2.8 on 2022-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectiveinterviewquestions',
            name='sub_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryinterviewquestions',
            name='sub_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
