# Generated by Django 4.0.2 on 2022-02-15 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20220129_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.TextField()),
                ('note', models.TextField()),
                ('created', models.DateTimeField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviews')),
            ],
        ),
    ]
