# Generated by Django 3.2.8 on 2021-11-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_auto_20211124_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedJobsNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_id', models.PositiveIntegerField()),
                ('receivers', models.PositiveIntegerField()),
                ('readers', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_jobs', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DirectEmployerNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_recieved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
            ],
        ),
        migrations.CreateModel(
            name='DirectEmployeeNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_recieved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
