# Generated by Django 4.0.2 on 2022-02-15 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0005_usernotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
