# Generated by Django 4.0.2 on 2022-02-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_employee_user_alter_employer_user'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatchannels',
            name='group',
            field=models.ManyToManyField(related_name='chat_group', to='api.User'),
        ),
        migrations.AlterField(
            model_name='chatchannels',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to='api.user'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='api.user'),
        ),
    ]
