# Generated by Django 4.0.2 on 2022-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_dmchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatchannels',
            name='chat_uid',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
